[workspace]
resolver = "2"

members = ["day-*", "aoc_utils"]
default-members = ["day-*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace.dependencies]
include-lines = "1.1.2"